### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by nvincenthill** [Harubex/scryfall#2]
Thanks for making this this. I have a question: how would I got about doing a fuzzy search by name? I'm relatively new to coding so I apologize if this is a dumb question. Example from source: https://scryfall.com/docs/api/cards/named

Thanks,

Nick

**Comment by Harubex** [comment]
Hey there. I went ahead and added a search by name function since one didn't exist. You should be able to call the `getCardByName()` function and get the result you want. Here's some examples:

```js
const scryfall = require("scryfall");

// With promises & exact search.
try {
    const card = await scryfall.getCardByName("counterspell");
} catch (err) {
    // err will be an error object if search is ambiguous.
}

// With callback & fuzzy search.
scryfall.getCardByName("jace, vry", true, (err, card) => {
    // card will contain the card data if search returns only 1 result.
});
```
