### ISSUE TITLE
Feature Request: explicit card request variants

### ISSUE THREAD

**Issue by SumNeuron** [Harubex/scryfall#3]
I have my own scryfall wrapper, but would be willing to contribute to yours / use yours provided documentation would be expanded and addition of card name based requests (users often work with card names, not identifiers) e.g. 

```js
scryfall.cards.exact(<exact-card-name>)
// calls: https://api.scryfall.com/cards/named?exact=<name>
```

**Comment by Harubex** [comment]
Hi there,

I plan on putting together documentation for this when I get some time. I'm just not sure when that'll be. For now, I added the search by name method. The card methods are still in the process of being fleshed out. If you'd like to contribute, that'd be the place to start.

Thanks.

**Comment by SumNeuron** [comment]
Sure. How are you providing as framework? Roll up?
